# Generated by Django 4.2.8 on 2023-12-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=1000)),
                ("answer", models.CharField(max_length=1000)),
            ],
        ),
    ]
