# Generated by Django 4.2.8 on 2024-03-05 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0002_card_revised"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="revision_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
