# Generated by Django 4.2.8 on 2024-02-29 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0002_card_revised"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="revision_date",
            field=models.DateField(default=datetime.date(2024, 2, 29)),
        ),
    ]
