# Generated by Django 4.2.8 on 2024-03-08 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0003_card_revision_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="revised",
        ),
        migrations.AddField(
            model_name="card",
            name="revision_time_delta",
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
