# Generated by Django 4.2.8 on 2024-04-04 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0005_card_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="creation_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
